### ISSUE TITLE
.downcase! parsing error

### ISSUE THREAD

**Issue by fjlj** [BenTearzz/RubyTwitchChatbot#2]
lines 51 and 52 of CommandsHandler.rb reads
`original_message.strip!
message = original_message.downcase!`

we see .strip! being used to remove any additional spaces after the message and save that in  original_message. -good, this is proper..

next on line 52 we see .downcase! being used to save original_message in all lower case, AND save that to a new variable message.. - This is not going to work..

downcase! returns a string ONLY IF it had to change anything.. otherwise it returns NIL. 

This attempt at double duty (updating original message and making a copy of it into a new variable message) will result in message being nil when the original_message had no capital letters in it... 

if updating original_message is not important changing this line to 
`message = original_message.downcase` 
will work just fine.. 

however original_message is used again further in the code implying that it should too be downcase.
to solve this.. we should simply add
`original_message.downcase!` 
below
`original_message.strip!`

and then update 
`message = original_message.downcase!`
to simply...
`message = original_message` OR `message = original_message.dup`(if changes should not effect eachother)

**Comment by benstigsen** [comment]
Hi, sorry for the very very very late reply, I didn't think anyone had opened an issue on this project. This is no longer an issue, the chat bot has been completely rewritten, it is now much more simple and organized.
